CREATE TABLE VTM_SESSION (
  session_nr SERIAL PRIMARY KEY,
  storyteller_nr BIGINT UNSIGNED NOT NULL DEFAULT 0,
  KEY FK_VTM_SESSION (storyteller_nr),
  CONSTRAINT FK_VTM_SESSION FOREIGN KEY (storyteller_nr) REFERENCES VTM_USER (user_nr)
);