CREATE TABLE VTM_ACTIVE_SESSION (
  session_nr BIGINT UNSIGNED NOT NULL DEFAULT 0,
  user_nr BIGINT UNSIGNED NOT NULL DEFAULT 0,
  character_nr BIGINT UNSIGNED NOT NULL DEFAULT 0,
  character_version_uid BIGINT UNSIGNED NOT NULL DEFAULT 1,
  CONSTRAINT PF_VTM_ACTIVE_SESSION PRIMARY KEY (session_nr, user_nr, character_nr),
  KEY FK_VTM_ACTIVE_SESSION_00 (session_nr),
  CONSTRAINT FK_VTM_ACTIVE_SESSION_00 FOREIGN KEY (session_nr) REFERENCES VTM_SESSION (session_nr),
  KEY FK_VTM_ACTIVE_SESSION_01 (user_nr),
  CONSTRAINT FK_VTM_ACTIVE_SESSION_01 FOREIGN KEY (user_nr) REFERENCES VTM_USER (user_nr),
  KEY FK_VTM_ACTIVE_SESSION_02 (character_nr),
  CONSTRAINT FK_VTM_ACTIVE_SESSION_02 FOREIGN KEY (character_nr) REFERENCES VTM_CHARACTER (character_nr)
);