CREATE TABLE VTM_CHARACTER (
  character_nr SERIAL PRIMARY KEY,
  version_uid BIGINT UNSIGNED NOT NULL DEFAULT 1,
  json_data JSON NOT NULL,
  user_nr BIGINT UNSIGNED NOT NULL DEFAULT 0,
  KEY FK_VTM_CHARACTER (user_nr),
  CONSTRAINT FK_VTM_CHARACTER FOREIGN KEY (user_nr) REFERENCES VTM_USER (user_nr)
);